### ISSUE TITLE
Crashes on network connection error

### ISSUE THREAD

**Issue by F4stFr3ddy** [F4stFr3ddy/homebridge-jablotron-alarm#26]
This was the same error as I once had before. Looks like this case is not properly caught as an exception and still feeds an empty response back.

```[2/17/2019, 1:52:46 PM] [Jablotron] Error: getaddrinfo EAI_AGAIN api.jablonet.net:443
[2/17/2019, 1:52:46 PM] [Jablotron] { Error: getaddrinfo EAI_AGAIN api.jablonet.net:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.jablonet.net',
  host: 'api.jablonet.net',
  port: 443 }
[2/17/2019, 1:53:46 PM] [Jablotron] Error: getaddrinfo EAI_AGAIN api.jablonet.net:443
[2/17/2019, 1:53:46 PM] [Jablotron] { Error: getaddrinfo EAI_AGAIN api.jablonet.net:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.jablonet.net',
  host: 'api.jablonet.net',
  port: 443 }
/opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron.js:82
                    var segments = response['data']['service_data'][0]['data'][0]['data']['segments'];
                                                                                 ^

TypeError: Cannot read property 'data' of undefined
    at /opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron.js:82:82
    at /opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:20:17
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:56:17)  
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by misncz** [comment]
That must be from some older version. We don't have that code line available in new version

**Comment by F4stFr3ddy** [comment]
I'll check, it should pull the latest version every night. Closing for now.
