### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by grzegorz914** [F4stFr3ddy/homebridge-jablotron-alarm#44]
Hi,

please look at this crashlog:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:56:38)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by MaLi812** [comment]
Same here. And no sign in MyJablotron-App possible. Maybe a server problem?

**Comment by misncz** [comment]
Yes, server problem

**Comment by grzegorz914** [comment]
if server make problems, plugin cannot crash the homebridge

**Comment by F4stFr3ddy** [comment]
@grzegorz914 you are right, it is not programmed defensively enough. But I'm not sure what we should give back if the system is down, I'm not aware of a state of error. 

And I would prefer to see an error than to have it return some value and not knowing if that value is the actual value or an error value.

Any ideas?

**Comment by grzegorz914** [comment]
Now we get this without Homebridge crash:

```
[3/5/2020, 7:37:58 PM] [Alarm] {
  status: false,
  error_status: 'service_unavailable',
  error_message: 'The service is not available.',
  checksum: '01b7cd8d40b14b97cbe8364440d285c1',
  server_id: '3523069-1583433477',
  client_id: null
}
[3/5/2020, 7:37:58 PM] [Alarm] Error: service_unavailable
    at /usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:56:17)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
If server id down return error value and prevent homebridge crash.

**Comment by F4stFr3ddy** [comment]
Ok gotcha. 

The server seems to be working again, however for me Home app still does not update.

**Comment by F4stFr3ddy** [comment]
New error:
```
[3/5/2020, 7:16:23 PM] [Jablotron] { Error: getaddrinfo EAI_AGAIN api.jablonet.net api.jablonet.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.jablonet.net',
  host: 'api.jablonet.net',
  port: 443 }```
