### ISSUE TITLE
Jablotron - The service is unavailable

### ISSUE THREAD

**Issue by Martinx64** [F4stFr3ddy/homebridge-jablotron-alarm#49]
Hello, i have installed homebridge to my Raspberry Pi 4 - Ubuntu 18.04. I have installed Jablotron plugin directly from Homebridge UI. I succesfully added bridge to my homekit and accesory is showing in my Home app, but it doesnt working. There is status in homebridge, that Jablotron service is unavailable.

Please could someone help me?

Thank you

**Comment by F4stFr3ddy** [comment]
Could you take a look at the homebridge logs and let us know if there are any message regarding Jablotron? Most likely:

1. You did not activate the account used by Homebridge for Jablotron
2. Incorrect user, password, pincode

**Comment by Martinx64** [comment]
Hello, thank you for your response :)

Could you take a look at the homebridge logs and let us know if there are
any message regarding Jablotron? Most likely:


Iam using normal jablotron account, which i am using also for myjablotron
application.


   1. You did not activate the account used by Homebridge for Jablotron - How
   do you mean, that maybe i did not activated account used for homebridge? Do
   i need somehow activate account?
   2. Incorrect user, password, pincode - User, password, pincode are
   correct


This is log when i try control jablotron device from my iPhone.
Log bellow
__________________________________________________________________________________________________________________
[8/9/2020, 11:33:51 AM] [Jablotron] Error:
    at
/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
    at IncomingMessage.<anonymous>
(/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:57:21)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[8/9/2020, 11:33:51 AM] [Jablotron] About to update state for accessory
[section_1] : update = true; cachedState = null; newState = null
[8/9/2020, 11:33:51 AM] [Jablotron] Refreshing status for Jablotron service
12345
[8/9/2020, 11:33:52 AM] [Jablotron] {
  status: false,
  error_status: 'service_unavailable',
  error_message: 'The service is not available.',
  checksum: 'ac3c7c2d48dd8e1a4b468d37ea4dcd24',
  server_id: '5961802-1596965632',
  client_id: null
}
[8/9/2020, 11:33:52 AM] [Jablotron] Error: service_unavailable
    at
/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
    at IncomingMessage.<anonymous>
(/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:57:21)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[8/9/2020, 11:33:52 AM] [Jablotron] Status refreshed for Jablotron service
12345
___________________________________________________________________________________________________

Thank you
Martin




ne 9. 8. 2020 o 10:39 Fred de Gier <notifications@github.com> napísal(a):

**Comment by F4stFr3ddy** [comment]
You're account seems to be fine. How did you receive the service id?

**Comment by Martinx64** [comment]
The service id “12345” was predefined in configuration tool. Should i
change it?

Dňa ne 9. 8. 2020 o 12:03 Fred de Gier <notifications@github.com>
napísala(a):

**Comment by F4stFr3ddy** [comment]
Yes, you need to adjust it to your service id, which can be found with the config helper: https://github.com/F4stFr3ddy/homebridge-jablotron-alarm#identify-jablotron-services-and-devices

**Comment by Martinx64** [comment]
Great, it is working now, thank you.

Can i ask you something else?

1. Is there any way to control more sections with, one click? How should i
setup “segment id” and “segment key” in config? Maybe “State_1_2_3”?

2. How can i setup night scene?

Dňa ne 9. 8. 2020 o 12:20 Fred de Gier <notifications@github.com>
napísala(a):

**Comment by misncz** [comment]
You can create automation action in Home that can arm/partially arm/disarm more sections based on your requirements

What do you call night mode?

**Comment by Martinx64** [comment]
When i controll accessory and i click “Night” (see picture), there is no
response. How can i setup this button in config?

Thank you

Dňa ne 9. 8. 2020 o 13:02 misncz <notifications@github.com> napísala(a):

**Comment by misncz** [comment]
Homekit itself (not the plugin) offers 4 “states” for alarms - Home/Away/Night (all these are for armed/partially armed) and Off (disarmed)
The plugin uses Away and Off (alarm on and off) and Home (alarm partially armed - if I remember well this one can be remapped to Night for example, works only if your unit has at least one section configured for partial arming)

**Comment by Martinx64** [comment]
Thank you. Is there way to setup in config, that one accessory will arm or
disarm all my sections?

Dňa ne 9. 8. 2020 o 13:28 misncz <notifications@github.com> napísala(a):

**Comment by misncz** [comment]
In Home app create new scene Alarm On, add all sections to it with armed state
