### ISSUE TITLE
After cookie expiration, program crashes

### ISSUE THREAD

**Issue by F4stFr3ddy** [F4stFr3ddy/homebridge-jablotron-alarm#7]
[12/1/2018, 12:17:31 PM] [Alarm System] Getting current state
[12/1/2018, 12:17:31 PM] [Alarm System] Using cached sessionId.
[12/1/2018, 12:17:31 PM] [Alarm System] { status: false,
  error_status: 'not_logged_in',
  checksum: '4e0a5f2250e13b14583a900483a182cb',
  server_id: '6129673-1543666642',
  client_id: null }
/opt/node/lib/node_modules/homebridge-jablotron/Jablotron/jablotronClient.js:24
                throw Error(response['error_status']);
                ^

Error: not_logged_in
    at Error (native)
    at /opt/node/lib/node_modules/homebridge-jablotron/Jablotron/jablotronClient.js:24:23
    at IncomingMessage.resp.on (/opt/node/lib/node_modules/homebridge-jablotron/Jablotron/jablotronClient.js:53:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by F4stFr3ddy** [comment]
Fixed.
